### ISSUE TITLE
Utilize slack attachments

### ISSUE THREAD

**Issue by kulttuuri** [kulttuuri/slack_mediawiki#12]
Format all that diff and links etc. to come inside [slack attachments](https://api.slack.com/docs/message-attachments#when_to_use_attachments). That could improve readability of the message. Slack seems to have added nice way to actually create formatted messages in [web interface](https://api.slack.com/docs/messages/builder?msg=%7B%22attachments%22%3A%5B%7B%22fallback%22%3A%22New%20ticket%20from%20Andrea%20Lee%20-%20Ticket%20%231943%3A%20Can%27t%20rest%20my%20password%20-%20https%3A%2F%2Fgroove.hq%2Fpath%2Fto%2Fticket%2F1943%22%2C%22pretext%22%3A%22New%20ticket%20from%20Andrea%20Lee%22%2C%22title%22%3A%22Ticket%20%231943%3A%20Can%27t%20reset%20my%20password%22%2C%22title_link%22%3A%22https%3A%2F%2Fgroove.hq%2Fpath%2Fto%2Fticket%2F1943%22%2C%22text%22%3A%22Help!%20I%20tried%20to%20reset%20my%20password%20but%20nothing%20happened!%22%2C%22color%22%3A%22%237CD197%22%7D%5D%7D) for testing them before actually implementing.

Would be great to first make suggestion of how the message would look like in that slack message builder interface and paste here url for that for discussion.

**Comment by Meneth** [comment]
Not sure it really does much to help. [Here](https://api.slack.com/docs/messages/builder?msg=%7B%22attachments%22%3A%5B%7B%22fallback%22%3A%22Meneth%20(block%20%7C%20groups%20%7C%20talk%20%7C%20contribs)%20has%20edited%20article%5Cn%20Unit%20types%20(edit%20%7C%20delete%20%7C%20history%20%7C%20diff)%22%2C%22text%22%3A%22%3Chttps%3A%2F%2Fapi.slack.com%2F%7CMeneth%3E%20(%3Chttps%3A%2F%2Fapi.slack.com%2F%7Cblock%3E%20%7C%20%3Chttps%3A%2F%2Fapi.slack.com%2F%7Cgroups%3E%20%7C%20%3Chttps%3A%2F%2Fapi.slack.com%2F%7Ctalk%3E%20%7C%20%3Chttps%3A%2F%2Fapi.slack.com%2F%7Ccontribs%3E)%20has%20edited%20article%5Cn%20%3Chttps%3A%2F%2Fapi.slack.com%2F%7CUnit%20types%3E%20(%3Chttps%3A%2F%2Fapi.slack.com%2F%7Cedit%3E%20%7C%20%3Chttps%3A%2F%2Fapi.slack.com%2F%7Cdelete%3E%20%7C%20%3Chttps%3A%2F%2Fapi.slack.com%2F%7Chistory%3E%20%7C%20%3Chttps%3A%2F%2Fapi.slack.com%2F%7Cdiff%3E)%22%2C%22fields%22%3A%5B%7B%22title%22%3A%22Summary%20(%2B5%20bytes)%3A%22%2C%22value%22%3A%22Lorem%20ipsum%20dolor%20sit%20amet%2C%20consectetur%20adipiscing%20elit.%20Etiam%20venenatis%20consequat%20lectus%20a%20aliquet.%22%7D%5D%2C%22color%22%3A%22%23F35A00%22%7D%5D%7D)'s a draft of sorts though:.

**Comment by kulttuuri** [comment]
Yup, doesn't look like it's very useful for now. Only thing I think this would be useful to have is for green color for newly added articles, orange for edits and red for removal of articles. But I think what is there currently (aka. no color coding) works pretty well already. Thoughts? :)

**Comment by Meneth** [comment]
I think simply adding the color would probably be pretty easy (only potential difficulty I see is handling the links in the fallback), though I'm not sure if it is particularly useful, yeah.

**Comment by kulttuuri** [comment]
Yep, not sure if it's useful right now. Closing this thread for now.
