### ISSUE TITLE
Works also with Mattermost

### ISSUE THREAD

**Issue by marove2000** [kulttuuri/slack_mediawiki#14]
I just want to give the information, that this extension also works perfectly with Mattermost (Slack alternative). Thanks for the great work.

**Comment by kulttuuri** [comment]
Awesome! What tweaking did you do with settings to get it working?

**Comment by marove2000** [comment]
No tweaking necessary. You have to create an incoming webhook in Mattermost (similar to Slack) and enter the URL at $wgSlackIncomingWebhookUrl
Also all additional options like $wgSlackIncludeUserUrls are working.

**Comment by kulttuuri** [comment]
Fantastic. Closing this and referring to it if someone asks 👍
