### ISSUE TITLE
Support for Discord

### ISSUE THREAD

**Issue by AlexJFox** [kulttuuri/slack_mediawiki#17]
Hi, Do you have plans to adapt this to support Discord servers? Discord supports per-channel/per-server webhooks but I assume the method is slightly different, I tried my luck and put Discord webhook details in  the config but no luck :)

Thanks in advance for reading!

**Comment by kulttuuri** [comment]
I have not yet. Do they support similar webhooks? I could take a look at discord when I have more time.

**Comment by kulttuuri** [comment]
Ah, in the morning my reading abilities are not the best 😆 Yes, so I will take a look at discord when I have more time (trying to do that next weekend). I'll probably create another repository if I get that working.

**Comment by AlexJFox** [comment]
Hey! I believe they are very similar, although I'm none too experienced in this field. The documentation is all here: https://discordapp.com/developers/docs/resources/webhook

Thanks for the reply, hopefully you get time to look it over!

**Comment by kulttuuri** [comment]
It actually does send the message if you add /slack to the end of the discord webhook URL but discord does not support all parameters of Slack (mostly the <url|name> formatting). Looking into this now.

**Comment by kulttuuri** [comment]
Ive just got Discord notifications working, I'm in progress of creating new project for discord notifications in github, will let you know once it's ready so you can give a spin for it! :)

**Comment by kulttuuri** [comment]
Ok! Can you follow the instructions on the new project page, download the extension and let me know here if that worked or if there we're any problems? discord_mediawiki extension is here: https://github.com/kulttuuri/discord_mediawiki

After it is working, I can also make a wiki article to mediawiki extensions page about that extension. Thanks! :)

**Comment by AlexJFox** [comment]
Hey, thanks so much! As soon as I finish work I'll give it a blast and let you know!

Thanks again!

**Comment by AlexJFox** [comment]
Hey, it works absolutely perfectly! Thanks so much, you're awesome!

**Comment by kulttuuri** [comment]
Fantastic :)
