### ISSUE TITLE
Provide an option to not show user email addresses

### ISSUE THREAD

**Issue by javawizard** [kulttuuri/slack_mediawiki#19]
What it says on the tin - I'd like to be able to `$wgSlackIncludeUserEmails = false` and have it not include user email addresses in new user notifications.

**Comment by kulttuuri** [comment]
In which actions does the user email come in? When users create accounts or?

**Comment by kulttuuri** [comment]
I've added this functionality for version 1.07: https://github.com/kulttuuri/slack_mediawiki/releases/tag/v1.07
