### ISSUE TITLE
$wgExcludedPermission doesn't seem to work

### ISSUE THREAD

**Issue by skonesam** [kulttuuri/slack_mediawiki#20]
Tried `$wgExcludedPermission = "Administrators";` and still get every notification pushed. 

I'm probably doing something wrong… any guesses what it might be?

(Thanks for this extension, btw. Love it!)

**Comment by kulttuuri** [comment]
@Meneth Ideas? :)

**Comment by Meneth** [comment]
It's exludedPermission, not excludedGroup.
Do something like this: 
```
$wgExcludedPermission = "slack-exempt";
$wgGroupPermissions['sysop']['slack-exempt'] = true;
```

**Comment by skonesam** [comment]
That did it — thank you!
