### ISSUE TITLE
curl_init() failure

### ISSUE THREAD

**Issue by skonesam** [kulttuuri/slack_mediawiki#24]
I'm a *huge* fan of this extension; it's a major part of my workflow. 

Updated basically everything on the server (Ubuntu 16.06, PHP 7, and MediaWiki 1.28) this morning, though, and ran into a problem. Installed curl `sudo apt-get install php-curl` and restarted the server; error remains the same.

So… any guesses what I'm doing wrong?

Thanks for creating such an awesome extension!

```
[4f1546bd9c53f8d999378587] /index.php?title=KENDALL_C._GEDNEY,_LTJG,_USN&action=submit Error from line 357 of /var/www/html/extensions/SlackNotifications/SlackNotificationsCore.php: Call to undefined function curl_init()

Backtrace:

#0 /var/www/html/extensions/SlackNotifications/SlackNotificationsCore.php(135): SlackNotifications::push_slack_notify(string, string, User)
#1 /var/www/html/includes/Hooks.php(195): SlackNotifications::slack_article_saved(WikiPage, User, WikitextContent, string, integer, NULL, NULL, integer, Revision, Status, boolean)
#2 /var/www/html/includes/page/WikiPage.php(1912): Hooks::run(string, array)
#3 /var/www/html/includes/libs/rdbms/database/Database.php(2682): WikiPage->{closure}(DatabaseMysqli, string)
#4 /var/www/html/includes/deferred/AtomicSectionUpdate.php(33): Database->doAtomicSection(string, Closure)
#5 /var/www/html/includes/deferred/DeferredUpdates.php(263): AtomicSectionUpdate->doUpdate()
#6 /var/www/html/includes/deferred/DeferredUpdates.php(225): DeferredUpdates::runUpdate(AtomicSectionUpdate, LBFactorySimple, integer)
#7 /var/www/html/includes/deferred/DeferredUpdates.php(129): DeferredUpdates::execute(array, string, integer)
#8 /var/www/html/includes/MediaWiki.php(592): DeferredUpdates::doUpdates(string, integer)
#9 /var/www/html/includes/MediaWiki.php(561): MediaWiki::preOutputCommit(RequestContext, Closure)
#10 /var/www/html/includes/MediaWiki.php(867): MediaWiki->doPreOutputCommit(Closure)
#11 /var/www/html/includes/MediaWiki.php(512): MediaWiki->main()
#12 /var/www/html/index.php(43): MediaWiki->run()
#13 {main}
```

**Comment by kulttuuri** [comment]
That's weird. Have you tried restarting your server? I think you might also need to have the curl library on your PATH variable and / or in the php.ini file extensions section.

Can you also try creating blank .php file with [phpinfo()](http://php.net/manual/en/function.phpinfo.php) call to verify that your PHP has the new CURL installed? :)

**Comment by skonesam** [comment]
Thanks for the reply! Definitely restarted; several times now, for various things. Also put Slack Notification back into localsettings.php to make sure the problem still exists.

> curl library on your server PATH variable and / or in the php.ini file extensions section

Not sure how to do the first part; going to Google momentarily. I think the php.ini file extensions section is below…

```
Additional .ini files parsed => //other stuff trimmed…
/etc/php/7.1/cli/conf.d/20-curl.ini,
```

Relevant parts of phpinfo() is below. Nothing jumps out at me.

```
curl

cURL support => enabled
cURL Information => 7.47.0
Age => 3
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => Yes
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => Yes
SPNEGO => Yes
SSL => Yes
SSPI => No
TLS-SRP => Yes
HTTP2 => No
GSSAPI => Yes
KERBEROS5 => Yes
UNIX_SOCKETS => Yes
PSL => No
Protocols => dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtmp, rtsp, smb, smbs, smtp, smtps, telnet, tftp
Host => x86_64-pc-linux-gnu
SSL Version => OpenSSL/1.0.2g
ZLib Version => 1.2.8
```

**Comment by skonesam** [comment]
PHP install failure. Took ```apt-get install php7.0-curl``` and a apache restart to get it working. So very odd.

Thanks for responding earlier, and thanks again for such a useful extension!

**Comment by kulttuuri** [comment]
Ah, that's weird. However glad you got it working after all! :)
