### ISSUE TITLE
Enable/disable notifications by namespace

### ISSUE THREAD

**Issue by berekuk** [kulttuuri/slack_mediawiki#26]
I'd like to disable notifications for the `User:` namespace, or to enable it just for the main namespace.

Rationale: people can be shy and avoid a wiki because they know that everyone else on the team will jump on their drafts immediately and start discussions prematurely. So I'd like to offer them a usage pattern where they write a draft in `User:Username/Draft` first and move it over to the main namespace when it's finished.

**Comment by kulttuuri** [comment]
Just committed support for this and the parameter wgSlackExcludeNotificationsFrom is also now documented in readme file. Would be great if you could give it a try and let me know that it works, thanks! :)

**Comment by berekuk** [comment]
Thanks! It works as expected.

**Comment by kulttuuri** [comment]
Fantastic! Thank you for testing it out :)

**Comment by berekuk** [comment]
I've found one minor issue: renaming a page still results in a notification.

I guess it would be better to do a check in that case too (for both an old name and a new name).

**Comment by kulttuuri** [comment]
Pushed out version 1.13 which adds support for checking article names when moving them! :)
