### ISSUE TITLE
Change $wgSlackFromName default to $wgSitename

### ISSUE THREAD

**Issue by labster** [kulttuuri/slack_mediawiki#5]
Could you make the default value for `$wgSlackFromName = `[`$wgSitename`](https://www.mediawiki.org/wiki/Manual:$wgSitename)?  We're probably going to install it on the @miraheze wiki farm, and that would make default config a little easier.  And it seems like a sane enough value.

I'm the security reviewer over at Miraheze, and it looks like a pretty good extension to me.  Thanks.

**Comment by kulttuuri** [comment]
Great idea! Let me change that :) 👍

**Comment by kulttuuri** [comment]
Done and committed!
